In [5]:
import pandas as pd
loans_2007 = pd.read_csv("loans_2007.csv",low_memory=False)
loans_2007.drop_duplicates()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,last_pymnt_amnt,last_credit_pull_d,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,pub_rec_bankruptcies,tax_liens
0,1077501,1296599.0,5000.0,5000.0,4975.000000,36 months,10.65%,162.87,B,B2,...,171.62,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
1,1077430,1314167.0,2500.0,2500.0,2500.000000,60 months,15.27%,59.83,C,C4,...,119.66,Sep-2013,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
2,1077175,1313524.0,2400.0,2400.0,2400.000000,36 months,15.96%,84.33,C,C5,...,649.91,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
3,1076863,1277178.0,10000.0,10000.0,10000.000000,36 months,13.49%,339.31,C,C1,...,357.48,Apr-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
4,1075358,1311748.0,3000.0,3000.0,3000.000000,60 months,12.69%,67.79,B,B5,...,67.79,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
5,1075269,1311441.0,5000.0,5000.0,5000.000000,36 months,7.90%,156.46,A,A4,...,161.03,Jan-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
6,1069639,1304742.0,7000.0,7000.0,7000.000000,60 months,15.96%,170.08,C,C5,...,1313.76,May-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
7,1072053,1288686.0,3000.0,3000.0,3000.000000,36 months,18.64%,109.43,E,E1,...,111.34,Dec-2014,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
8,1071795,1306957.0,5600.0,5600.0,5600.000000,60 months,21.28%,152.39,F,F2,...,152.39,Aug-2012,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
9,1071570,1306721.0,5375.0,5375.0,5350.000000,60 months,12.69%,121.45,B,B5,...,121.45,Mar-2013,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
10,1070078,1305201.0,6500.0,6500.0,6500.000000,60 months,14.65%,153.45,C,C3,...,1655.54,Dec-2015,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
11,1069908,1305008.0,12000.0,12000.0,12000.000000,36 months,12.69%,402.54,B,B5,...,6315.30,Aug-2013,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
12,1064687,1298717.0,9000.0,9000.0,9000.000000,36 months,13.49%,305.38,C,C1,...,305.38,Nov-2012,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
13,1069866,1304956.0,3000.0,3000.0,3000.000000,36 months,9.91%,96.68,B,B1,...,102.43,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
14,1069057,1303503.0,10000.0,10000.0,10000.000000,36 months,10.65%,325.74,B,B2,...,325.74,Mar-2014,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
15,1069759,1304871.0,1000.0,1000.0,1000.000000,36 months,16.29%,35.31,D,D1,...,36.32,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
16,1065775,1299699.0,10000.0,10000.0,10000.000000,36 months,15.27%,347.98,C,C4,...,370.46,Apr-2015,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
17,1069971,1304884.0,3600.0,3600.0,3600.000000,36 months,6.03%,109.57,A,A1,...,583.45,May-2014,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
18,1062474,1294539.0,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,16.98,Jul-2015,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
19,1069742,1304855.0,9200.0,9200.0,9200.000000,36 months,6.03%,280.01,A,A1,...,8061.10,Feb-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
20,1069740,1284848.0,20250.0,20250.0,19142.161077,60 months,15.27%,484.63,C,C4,...,6024.09,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
21,1039153,1269083.0,21000.0,21000.0,21000.000000,36 months,12.42%,701.73,B,B4,...,701.73,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
22,1069710,1304821.0,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,349.21,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
23,1069700,1304810.0,10000.0,10000.0,10000.000000,36 months,11.71%,330.76,B,B3,...,4942.63,Mar-2014,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
24,1069559,1304634.0,6000.0,6000.0,6000.000000,36 months,11.71%,198.46,B,B3,...,198.46,Mar-2013,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
25,1069697,1273773.0,15000.0,15000.0,15000.000000,36 months,9.91%,483.38,B,B1,...,2447.05,Sep-2012,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
26,1069800,1304679.0,15000.0,15000.0,8725.000000,36 months,14.27%,514.64,C,C2,...,0.00,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
27,1069657,1304764.0,5000.0,5000.0,5000.000000,60 months,16.77%,123.65,D,D2,...,123.65,May-2013,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
28,1069799,1304678.0,4000.0,4000.0,4000.000000,36 months,11.71%,132.31,B,B3,...,2638.77,Jun-2016,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
29,1047704,1278806.0,8500.0,8500.0,8500.000000,36 months,11.71%,281.15,B,B3,...,581.59,Jan-2015,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42508,91175,91170.0,6000.0,6000.0,1200.000000,36 months,13.12%,202.51,D,D5,...,204.65,Sep-2012,NaN,1.0,INDIVIDUAL,0.0,NaN,0.0,NaN,NaN
42509,91126,91067.0,5350.0,5350.0,625.000000,36 months,13.12%,180.57,D,D5,...,1056.94,Jul-2013,NaN,1.0,INDIVIDUAL,0.0,NaN,0.0,NaN,NaN
42510,91023,70879.0,1900.0,1900.0,900.000000,36 months,9.64%,61.00,B,B4,...,0.00,May-2007,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42511,90106,90090.0,10000.0,10000.0,350.000000,36 months,14.70%,345.18,E,E5,...,1605.65,Aug-2010,NaN,1.0,INDIVIDUAL,0.0,NaN,0.0,NaN,NaN
42512,89258,80039.0,2000.0,2000.0,1275.000000,36 months,7.12%,61.87,A,A1,...,63.59,Jun-2010,NaN,1.0,INDIVIDUAL,0.0,NaN,0.0,NaN,NaN
42513,88637,88629.0,6000.0,6000.0,650.000000,36 months,10.59%,195.28,C,C2,...,197.36,Oct-2014,NaN,1.0,INDIVIDUAL,0.0,NaN,0.0,NaN,NaN
42514,88046,88023.0,4400.0,4400.0,1400.000000,36 months,9.64%,141.25,B,B4,...,143.28,Feb-2015,NaN,1.0,INDIVIDUAL,0.0,NaN,0.0,NaN,NaN
42515,85961,85923.0,1200.0,1200.0,500.000000,36 months,9.01%,38.17,B,B2,...,39.05,Jun-2016,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42516,85818,85802.0,5000.0,5000.0,375.000000,36 months,11.22%,164.23,C,C4,...,149.43,Apr-2010,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42517,85781,85727.0,1400.0,1400.0,475.000000,36 months,10.91%,45.78,C,C3,...,1.78,Sep-2014,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42518,85675,85667.0,1000.0,1000.0,625.000000,36 months,14.07%,34.21,E,E3,...,35.27,Jun-2010,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42519,84670,79576.0,5000.0,5000.0,300.000000,36 months,7.75%,156.11,A,A3,...,1663.91,Aug-2009,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42520,84098,84091.0,2500.0,2500.0,225.000000,36 months,7.43%,77.69,A,A2,...,0.00,Jun-2007,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42521,83979,83974.0,3000.0,3000.0,250.000000,36 months,7.43%,93.23,A,A2,...,0.00,Jun-2007,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42522,83489,83471.0,2600.0,2600.0,575.000000,36 months,8.38%,81.94,A,A5,...,21.75,Mar-2010,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42523,83185,83132.0,1000.0,1000.0,625.000000,36 months,7.12%,30.94,A,A1,...,32.93,Apr-2014,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42524,74014,73890.0,6450.0,6450.0,0.000000,36 months,11.22%,211.85,C,C4,...,167.78,Jun-2010,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42525,76629,76623.0,1275.0,1275.0,0.000000,36 months,12.49%,42.65,D,D3,...,42.65,Jun-2016,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42526,81085,80973.0,10500.0,10500.0,275.000000,36 months,11.22%,344.87,C,C4,...,0.00,Jun-2007,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42527,77792,77764.0,3000.0,3000.0,125.000000,36 months,9.01%,95.42,B,B2,...,95.66,Jun-2010,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42528,77757,70626.0,3000.0,3000.0,0.000000,36 months,9.33%,95.86,B,B3,...,96.77,May-2007,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42529,74505,74469.0,2000.0,2000.0,225.000000,36 months,9.96%,64.50,B,B5,...,0.84,Jul-2010,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42530,74323,74301.0,6500.0,6500.0,0.000000,36 months,9.64%,208.66,B,B4,...,208.65,Jun-2016,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42531,73582,73096.0,3500.0,3500.0,225.000000,36 months,10.28%,113.39,C,C1,...,0.00,Feb-2013,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42532,72998,72992.0,1000.0,1000.0,0.000000,36 months,9.64%,32.11,B,B4,...,32.41,Sep-2014,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42533,72176,70868.0,2525.0,2525.0,225.000000,36 months,9.33%,80.69,B,B3,...,82.03,May-2007,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42534,71623,70735.0,6500.0,6500.0,0.000000,36 months,8.38%,204.84,A,A5,...,205.32,Aug-2007,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42535,70686,70681.0,5000.0,5000.0,0.000000,36 months,7.75%,156.11,A,A3,...,156.39,Feb-2015,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,NaN,NaN
42536,Total amount funded in policy code 1: 471701350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42537,Total amount funded in policy code 2: 0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
print(loans_2007.iloc[0])
print(loans_2007.shape[1])

id                                1077501
member_id                      1.2966e+06
loan_amnt                            5000
funded_amnt                          5000
funded_amnt_inv                      4975
term                            36 months
int_rate                           10.65%
installment                        162.87
grade                                   B
sub_grade                              B2
emp_title                             NaN
emp_length                      10+ years
home_ownership                       RENT
annual_inc                          24000
verification_status              Verified
issue_d                          Dec-2011
loan_status                    Fully Paid
pymnt_plan                              n
purpose                       credit_card
title                            Computer
zip_code                            860xx
addr_state                             AZ
dti                                 27.65
delinq_2yrs                             0
earliest_cr_line                 Jan-1985
inq_last_6mths                          1
open_acc                                3
pub_rec                                 0
revol_bal                           13648
revol_util                          83.7%
total_acc                               9
initial_list_status                     f
out_prncp                               0
out_prncp_inv                           0
total_pymnt                       5863.16
total_pymnt_inv                   5833.84
total_rec_prncp                      5000
total_rec_int                      863.16
total_rec_late_fee                      0
recoveries                              0
collection_recovery_fee                 0
last_pymnt_d                     Jan-2015
last_pymnt_amnt                    171.62
last_credit_pull_d               Jun-2016
collections_12_mths_ex_med              0
policy_code                             1
application_type               INDIVIDUAL
acc_now_delinq                          0
chargeoff_within_12_mths                0
delinq_amnt                             0
pub_rec_bankruptcies                    0
tax_liens                               0
Name: 0, dtype: object
52

In [7]:
loans_2007 = loans_2007.drop(["id", "member_id", "funded_amnt", "funded_amnt_inv", "grade", "sub_grade", "emp_title", "issue_d"], axis=1)

In [8]:
loans_2007 = loans_2007.drop(["zip_code", "out_prncp", "out_prncp_inv", "total_pymnt", "total_pymnt_inv", "total_rec_prncp"], axis=1)

In [9]:
loans_2007 = loans_2007.drop(["total_rec_int", "total_rec_late_fee", "recoveries", "collection_recovery_fee", "last_pymnt_d", "last_pymnt_amnt"], axis=1)
print(loans_2007.iloc[0])
print(loans_2007.shape[1])

loan_amnt                            5000
term                            36 months
int_rate                           10.65%
installment                        162.87
emp_length                      10+ years
home_ownership                       RENT
annual_inc                          24000
verification_status              Verified
loan_status                    Fully Paid
pymnt_plan                              n
purpose                       credit_card
title                            Computer
addr_state                             AZ
dti                                 27.65
delinq_2yrs                             0
earliest_cr_line                 Jan-1985
inq_last_6mths                          1
open_acc                                3
pub_rec                                 0
revol_bal                           13648
revol_util                          83.7%
total_acc                               9
initial_list_status                     f
last_credit_pull_d               Jun-2016
collections_12_mths_ex_med              0
policy_code                             1
application_type               INDIVIDUAL
acc_now_delinq                          0
chargeoff_within_12_mths                0
delinq_amnt                             0
pub_rec_bankruptcies                    0
tax_liens                               0
Name: 0, dtype: object
32

In [10]:
print(loans_2007['loan_status'].value_counts())

Fully Paid                                             33136
Charged Off                                             5634
Does not meet the credit policy. Status:Fully Paid      1988
Current                                                  961
Does not meet the credit policy. Status:Charged Off      761
Late (31-120 days)                                        24
In Grace Period                                           20
Late (16-30 days)                                          8
Default                                                    3
Name: loan_status, dtype: int64

In [11]:
loans_2007 = loans_2007[(loans_2007['loan_status'] == "Fully Paid") | (loans_2007['loan_status'] == "Charged Off")]

status_replace = {
    "loan_status" : {
        "Fully Paid": 1,
        "Charged Off": 0,
    }
}

loans_2007 = loans_2007.replace(status_replace)

In [12]:
orig_columns = loans_2007.columns
drop_columns = []
for col in orig_columns:
    col_series = loans_2007[col].dropna().unique()
    if len(col_series) == 1:
        drop_columns.append(col)
loans_2007 = loans_2007.drop(drop_columns, axis=1)
print(drop_columns)

['pymnt_plan', 'initial_list_status', 'collections_12_mths_ex_med', 'policy_code', 'application_type', 'acc_now_delinq', 'chargeoff_within_12_mths', 'delinq_amnt', 'tax_liens']

In [14]:
#loans_2007.to_csv("filtered_loans_2007.csv", index=False)

## Preparing the features

In [17]:
loans = pd.read_csv('filtered_loans_2007.csv', encoding='Latin-1')
null_counts = loans.isnull().sum()
print(null_counts)

loan_amnt                 0
term                      0
int_rate                  0
installment               0
emp_length                0
home_ownership            0
annual_inc                0
verification_status       0
loan_status               0
purpose                   0
title                    10
addr_state                0
dti                       0
delinq_2yrs               0
earliest_cr_line          0
inq_last_6mths            0
open_acc                  0
pub_rec                   0
revol_bal                 0
revol_util               50
total_acc                 0
last_credit_pull_d        2
pub_rec_bankruptcies    697
dtype: int64

In [18]:
loans = loans.drop("pub_rec_bankruptcies", axis=1)
loans = loans.dropna(axis=0)
print(loans.dtypes.value_counts())

object     11
float64    10
int64       1
dtype: int64

In [19]:
object_columns_df = loans.select_dtypes(include=["object"])
print(object_columns_df.iloc[0])

term                     36 months
int_rate                    10.65%
emp_length               10+ years
home_ownership                RENT
verification_status       Verified
purpose                credit_card
title                     Computer
addr_state                      AZ
earliest_cr_line          Jan-1985
revol_util                   83.7%
last_credit_pull_d        Jun-2016
Name: 0, dtype: object

In [20]:
cols = ['home_ownership', 'verification_status', 'emp_length', 'term', 'addr_state']
for c in cols:
    print(loans[c].value_counts())

RENT        18513
MORTGAGE    17112
OWN          2984
OTHER          96
NONE            3
Name: home_ownership, dtype: int64
Not Verified       16696
Verified           12290
Source Verified     9722
Name: verification_status, dtype: int64
10+ years    8545
< 1 year     4513
2 years      4303
3 years      4022
4 years      3353
5 years      3202
1 year       3176
6 years      2177
7 years      1714
8 years      1442
9 years      1229
n/a          1032
Name: emp_length, dtype: int64
 36 months    29041
 60 months     9667
Name: term, dtype: int64
CA    6958
NY    3713
FL    2791
TX    2667
NJ    1798
IL    1483
PA    1473
VA    1376
GA    1364
MA    1301
OH    1179
MD    1026
AZ     850
WA     822
CO     770
NC     753
CT     730
MI     712
MO     671
MN     603
NV     481
SC     462
WI     441
AL     437
OR     436
LA     430
KY     315
OK     290
KS     260
UT     254
AR     237
DC     209
RI     196
NM     184
WV     172
NH     166
HI     166
DE     113
MT      83
WY      80
AK      78
SD      61
VT      53
MS      19
TN      17
IN       9
ID       6
NE       5
IA       5
ME       3
Name: addr_state, dtype: int64

In [21]:
print(loans["purpose"].value_counts())
print(loans["title"].value_counts())

debt_consolidation    18130
credit_card            5039
other                  3864
home_improvement       2897
major_purchase         2155
small_business         1762
car                    1510
wedding                 929
medical                 680
moving                  576
vacation                375
house                   369
educational             320
renewable_energy        102
Name: purpose, dtype: int64
Debt Consolidation                                     2104
Debt Consolidation Loan                                1632
Personal Loan                                           642
Consolidation                                           494
debt consolidation                                      485
Credit Card Consolidation                               353
Home Improvement                                        346
Debt consolidation                                      324
Small Business Loan                                     310
Credit Card Loan                                        305
Personal                                                302
Consolidation Loan                                      251
Home Improvement Loan                                   234
personal loan                                           227
personal                                                211
Loan                                                    208
Wedding Loan                                            201
Car Loan                                                195
consolidation                                           193
Other Loan                                              181
Credit Card Payoff                                      150
Wedding                                                 149
Credit Card Refinance                                   143
Major Purchase Loan                                     139
Consolidate                                             125
Medical                                                 118
Credit Card                                             115
home improvement                                        107
My Loan                                                  92
Credit Cards                                             91
                                                       ...
Laura's Debt Freedom Plan                                 1
Paul Family Loan                                          1
Freeatlast101                                             1
Moving to better job; help a veteran!                     1
Consumer Loan 36                                          1
mustafin                                                  1
No more                                                   1
Home Addition/Remodel                                     1
Viking Pool                                               1
S-Debt Loan                                               1
Clean Slate after Wedding                                 1
Dr. In Need of a Little Consolidation                     1
Business Loan to maximize opportunities                   1
Breath easier a month                                     1
Enough with the Credit Card Debt!                         1
JP's loan                                                 1
mortgage                                                  1
Chase Card Payoff                                         1
Responsible borrower                                      1
Help make me the happiest man alive                       1
move rebound                                              1
Doctor Loan                                               1
BIG MONEY MERGER                                          1
Amazon Card Refi                                          1
Sharp borrower who pays on time everytime                 1
consolitdation loan                                       1
More than 1/2 way out of debt, need help finishing.       1
pack it together                                          1
New laptop                                                1
England Drive Life                                        1
Name: title, Length: 19332, dtype: int64

In [22]:
mapping_dict = {
    "emp_length": {
        "10+ years": 10,
        "9 years": 9,
        "8 years": 8,
        "7 years": 7,
        "6 years": 6,
        "5 years": 5,
        "4 years": 4,
        "3 years": 3,
        "2 years": 2,
        "1 year": 1,
        "< 1 year": 0,
        "n/a": 0
    }
}
loans = loans.drop(["last_credit_pull_d", "earliest_cr_line", "addr_state", "title"], axis=1)
loans["int_rate"] = loans["int_rate"].str.rstrip("%").astype("float")
loans["revol_util"] = loans["revol_util"].str.rstrip("%").astype("float")
loans = loans.replace(mapping_dict)

In [23]:
cat_columns = ["home_ownership", "verification_status", "purpose", "term"]
dummy_df = pd.get_dummies(loans[cat_columns])
loans = pd.concat([loans, dummy_df], axis=1)
loans = loans.drop(cat_columns, axis=1)
print(loans.head())

   loan_amnt  int_rate  installment  emp_length  annual_inc  loan_status  \
0     5000.0     10.65       162.87          10     24000.0            1
1     2500.0     15.27        59.83           0     30000.0            0
2     2400.0     15.96        84.33          10     12252.0            1
3    10000.0     13.49       339.31          10     49200.0            1
4     5000.0      7.90       156.46           3     36000.0            1

     dti  delinq_2yrs  inq_last_6mths  open_acc       ...         \
0  27.65          0.0             1.0       3.0       ...
1   1.00          0.0             5.0       3.0       ...
2   8.72          0.0             2.0       2.0       ...
3  20.00          0.0             1.0      10.0       ...
4  11.20          0.0             3.0       9.0       ...

   purpose_major_purchase  purpose_medical  purpose_moving  purpose_other  \
0                       0                0               0              0
1                       0                0               0              0
2                       0                0               0              0
3                       0                0               0              1
4                       0                0               0              0

   purpose_renewable_energy  purpose_small_business  purpose_vacation  \
0                         0                       0                 0
1                         0                       0                 0
2                         0                       1                 0
3                         0                       0                 0
4                         0                       0                 0

   purpose_wedding  term_ 36 months  term_ 60 months
0                0                1                0
1                0                0                1
2                0                1                0
3                0                1                0
4                1                1                0

[5 rows x 38 columns]

In [24]:
# loans.to_csv("cleaned_loans_2007.csv", index=False)

## Making predictions

In [25]:
loans = pd.read_csv("cleaned_loans_2007.csv")
print(loans.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38708 entries, 0 to 38707
Data columns (total 38 columns):
loan_amnt                              38708 non-null float64
int_rate                               38708 non-null float64
installment                            38708 non-null float64
emp_length                             38708 non-null int64
annual_inc                             38708 non-null float64
loan_status                            38708 non-null int64
dti                                    38708 non-null float64
delinq_2yrs                            38708 non-null float64
inq_last_6mths                         38708 non-null float64
open_acc                               38708 non-null float64
pub_rec                                38708 non-null float64
revol_bal                              38708 non-null float64
revol_util                             38708 non-null float64
total_acc                              38708 non-null float64
home_ownership_MORTGAGE                38708 non-null int64
home_ownership_NONE                    38708 non-null int64
home_ownership_OTHER                   38708 non-null int64
home_ownership_OWN                     38708 non-null int64
home_ownership_RENT                    38708 non-null int64
verification_status_Not Verified       38708 non-null int64
verification_status_Source Verified    38708 non-null int64
verification_status_Verified           38708 non-null int64
purpose_car                            38708 non-null int64
purpose_credit_card                    38708 non-null int64
purpose_debt_consolidation             38708 non-null int64
purpose_educational                    38708 non-null int64
purpose_home_improvement               38708 non-null int64
purpose_house                          38708 non-null int64
purpose_major_purchase                 38708 non-null int64
purpose_medical                        38708 non-null int64
purpose_moving                         38708 non-null int64
purpose_other                          38708 non-null int64
purpose_renewable_energy               38708 non-null int64
purpose_small_business                 38708 non-null int64
purpose_vacation                       38708 non-null int64
purpose_wedding                        38708 non-null int64
term_ 36 months                        38708 non-null int64
term_ 60 months                        38708 non-null int64
dtypes: float64(12), int64(26)
memory usage: 11.2 MB
None

In [26]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
cols = loans.columns
train_cols = cols.drop("loan_status")
features = loans[train_cols]
target = loans["loan_status"]
lr.fit(features, target)
predictions = lr.predict(features)

In [28]:
from sklearn.cross_validation import cross_val_predict, KFold
lr = LogisticRegression()
kf = KFold(features.shape[0], random_state=1)
predictions = cross_val_predict(lr, features, target, cv=kf)
predictions = pd.Series(predictions)

# False positives.
fp_filter = (predictions == 1) & (loans["loan_status"] == 0)
fp = len(predictions[fp_filter])

# True positives.
tp_filter = (predictions == 1) & (loans["loan_status"] == 1)
tp = len(predictions[tp_filter])

# False negatives.
fn_filter = (predictions == 0) & (loans["loan_status"] == 1)
fn = len(predictions[fn_filter])

# True negatives
tn_filter = (predictions == 0) & (loans["loan_status"] == 0)
tn = len(predictions[tn_filter])

# Rates
tpr = tp / (tp + fn)
fpr = fp / (fp + tn)

print(tpr)
print(fpr)

0.9987912851660472
0.9967943009795192

In [29]:
# Add balanced class_weight
from sklearn.cross_validation import cross_val_predict
lr = LogisticRegression(class_weight="balanced")
kf = KFold(features.shape[0], random_state=1)
predictions = cross_val_predict(lr, features, target, cv=kf)
predictions = pd.Series(predictions)

# False positives.
fp_filter = (predictions == 1) & (loans["loan_status"] == 0)
fp = len(predictions[fp_filter])

# True positives.
tp_filter = (predictions == 1) & (loans["loan_status"] == 1)
tp = len(predictions[tp_filter])

# False negatives.
fn_filter = (predictions == 0) & (loans["loan_status"] == 1)
fn = len(predictions[fn_filter])

# True negatives
tn_filter = (predictions == 0) & (loans["loan_status"] == 0)
tn = len(predictions[tn_filter])

# Rates
tpr = tp / (tp + fn)
fpr = fp / (fp + tn)

print(tpr)
print(fpr)

0.6656996947995044
0.38682101513802314

In [30]:
# Add the penalty manually
from sklearn.cross_validation import cross_val_predict
penalty = {
    0: 10,
    1: 1
}

lr = LogisticRegression(class_weight=penalty)
kf = KFold(features.shape[0], random_state=1)
predictions = cross_val_predict(lr, features, target, cv=kf)
predictions = pd.Series(predictions)

# False positives.
fp_filter = (predictions == 1) & (loans["loan_status"] == 0)
fp = len(predictions[fp_filter])

# True positives.
tp_filter = (predictions == 1) & (loans["loan_status"] == 1)
tp = len(predictions[tp_filter])

# False negatives.
fn_filter = (predictions == 0) & (loans["loan_status"] == 1)
fn = len(predictions[fn_filter])

# True negatives
tn_filter = (predictions == 0) & (loans["loan_status"] == 0)
tn = len(predictions[tn_filter])

# Rates
tpr = tp / (tp + fn)
fpr = fp / (fp + tn)

print(tpr)
print(fpr)

0.2294140754842414
0.08156723063223509

## Random forest

In [32]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(class_weight="balanced", random_state=1)
kf = KFold(features.shape[0], random_state=1)
predictions = cross_val_predict(rf, features, target, cv=kf)
predictions = pd.Series(predictions)

# False positives.
fp_filter = (predictions == 1) & (loans["loan_status"] == 0)
fp = len(predictions[fp_filter])

# True positives.
tp_filter = (predictions == 1) & (loans["loan_status"] == 1)
tp = len(predictions[tp_filter])

# False negatives.
fn_filter = (predictions == 0) & (loans["loan_status"] == 1)
fn = len(predictions[fn_filter])

# True negatives
tn_filter = (predictions == 0) & (loans["loan_status"] == 0)
tn = len(predictions[tn_filter])

# Rates
tpr = tp / (tp + fn)
fpr = fp / (fp + tn)

print(tpr)
print(fpr)

0.971806726498051
0.9330365093499555